# Generated by Django 6.0 on 2025-12-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaploSor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('kezdet', models.TimeField()),
                ('veg', models.TimeField()),
                ('ido', models.DurationField()),
                ('tevekenyseg', models.TextField()),
                ('ertek', models.IntegerField(blank=True, null=True)),
                ('kategoria', models.CharField(blank=True, max_length=100)),
                ('kapcsolodo', models.CharField(blank=True, max_length=100)),
                ('szerep', models.CharField(blank=True, max_length=100)),
                ('erzelem', models.CharField(blank=True, max_length=100)),
                ('kapcsolodo_cel', models.CharField(blank=True, max_length=200)),
                ('letrehozva', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-datum', '-kezdet'],
            },
        ),
    ]
