# Generated by Django 6.0 on 2025-12-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naplo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naplosor',
            name='megjegyzes',
            field=models.TextField(blank=True),
        ),
    ]
