# Generated by Django 6.0 on 2025-12-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naplo', '0002_naplosor_megjegyzes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naplosor',
            name='kezdet',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='naplosor',
            name='veg',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
