# Generated by Django 6.0 on 2025-12-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naplo', '0003_alter_naplosor_kezdet_alter_naplosor_veg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('kategoria', 'Kategória'), ('kapcsolodo', 'Kapcsolódó'), ('szerep', 'Szerep'), ('erzelem', 'Érzelem'), ('cel', 'Kapcsolódó cél')], max_length=20)),
                ('nev', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['tipus', 'nev'],
                'unique_together': {('tipus', 'nev')},
            },
        ),
    ]
