# Generated by Django 6.0 on 2025-12-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naplo', '0004_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='naplosor',
            name='six_program_focus',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
