# Generated by ChatGPT on 2026-01-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naplo', '0005_naplosor_six_program_focus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naplosor',
            old_name='six_program_focus',
            new_name='eletkerek_focus',
        ),
    ]
